Handle key file path and empty passphrase properly

diff --git a/bin/executable_lpass-ssh-add b/bin/executable_lpass-ssh-add
--- a/bin/executable_lpass-ssh-add
+++ b/bin/executable_lpass-ssh-add
@@ -5,11 +5,24 @@
 	exit 1
 }
 
+if [ -f "$(realpath "$2")" ]; then
+	keyfile="$(realpath "$2")"
+elif [ -z "$keyfile" ] && [ -f "$(realpath "$HOME/.ssh/$2")" ]; then
+	keyfile="$(realpath "$HOME/.ssh/$2")"
+else
+	echo "Key file $2 is not found, exiting."
+	exit 1
+fi
+
 phrase=$(lpass show --notes "$1/phrase")
 
-expect <<EOF
-	   spawn ssh-add $HOME/.ssh/$2
+if [ -z "$phrase" ]; then
+	ssh-add "$keyfile"
+else
+	expect <<-EOF
+	   spawn ssh-add $keyfile
 	   expect "Enter passphrase"
 	   send "$phrase\r"
 	   expect eof
-EOF
+	EOF
+fi
