Use underscores in secret names instead of slashes
In order to use references, as per https://developer.1password.com/docs/cli/reference/commands/read

Reference names cannot contain special characters other than hyphens (-) and
underscores (_). If any part of a secret reference includes a whitespace,
enclose the entire secret reference in quotation marks.

diff --git a/bin/executable_op-ssh-keygen b/bin/executable_op-ssh-keygen
--- a/bin/executable_op-ssh-keygen
+++ b/bin/executable_op-ssh-keygen
@@ -26,8 +26,8 @@ name="$1"
 shift
 [ -n "$name" ] || usage
 
-pub=$(op document get "ssh/$name/public" 2>/dev/null)
-[ -z "$pub" ] || { echo "error: key $name/public already exists in LastPass."; exit 1; }
+pub=$(op document get "ssh_${name}_public" 2>/dev/null)
+[ -z "$pub" ] || { echo "error: key ${name}_public already exists in 1Password."; exit 1; }
 
 lastpwd="$PWD"
 tmpdir=$(mktemp -d)
@@ -36,11 +36,11 @@ cd "$tmpdir" || { echo "error: can't cd to tmpdir"; exit 1; }
 # source: https://gist.github.com/kraftb/9918106#gistcomment-2733298
 mkfifo -m 0600 key key.pub &&
 	(
-		op document create key --title "ssh/$name/private" --file-name "private"
-		op document create key.pub --title "ssh/$name/public" --file-name "public"
-		[ -n "$phrase" ] &&  op item create --category password --title "ssh/$name/phrase" "password=$phrase"
+		op document create key --title "ssh_${name}_private" --file-name "private"
+		op document create key.pub --title "ssh_${name}_public" --file-name "public"
+		[ -n "$phrase" ] &&  op item create --category password --title "ssh_${name}_phrase" "password=$phrase"
 	) &
-echo "y" | ssh-keygen -a "$ROUNDS" -N "$phrase" -C "$name-$(date "+%Y%m%d%H%M%S")" -f key "$@"
+echo "y" | ssh-keygen -a "$ROUNDS" -N "$phrase" -C "${name}-$(date "+%Y%m%d%H%M%S")" -f key "$@"
 
 rm key key.pub
 cd "$lastpwd" || { echo "warn: can't cd back to last dir"; exit 0; }
